# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Materials Informatics
author: 
logo: logo.png

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
  

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  deepnote_url: "https://deepnote.com"
  thebe: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/deng-group/MLE4217-5219  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-rmakeepository
html:
  use_issues_button: false
  use_repository_button: false
  home_page_in_navbar: false
  announcement: "👷‍♂️ As we are just launching this course, the content keeps updating! Please check back regularly for updates."
  extra_footer          : |
    <p>
    <img src='https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg' height='31'/>
    | © Copyright 2025 Zeyu Deng | <a href='https://matsci.dev'>DENG Group</a>
    </br>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </p>
  extra_navbar          : ''


#######################################################################################
# Advanced and power-user settings
sphinx:
#   extra_extensions          :   # A list of extra extensions to load by Sphinx (added to those already used by JB).
#   local_extensions          :   # A list of local extensions to load by sphinx specified by "name: path" items
#   recursive_update          : false # A boolean indicating whether to overwrite the Sphinx config (true) or recursively update (false)
  config :
    html_show_copyright : false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
#     latex_elements:
#       preamble: \usepackage{fontspec}
#       preamble: \pagestyle{fancy}
#       preamble: \fancyhf{}
#       preamble: \fancyhfoffset[L]{1cm}
#       preamble: \fancyhfoffset[R]{1cm}
#       preamble: \fancyhead[L]{MLE4217/5219 Materials Informatics}
#       preamble: \fancyhead[R]{\thepage}
#       preamble: \rfoot{}
#       preamble: \setmainfont{Avenir}
#       preamble: \geometry{tmargin=.75in, bmargin=.75in, lmargin=.75in, rmargin = .75in}

